export type TransitFareMode =
  | 'bus'
  | 'rail'
  | 'light_rail'
  | 'subway'
  | 'commuter_rail'
  | 'streetcar';

export type TransitFareRule = {
  id: string;
  agencyName: string;
  city: string;
  state: string;
  country: 'US';
  regionKeys: string[];
  modes: TransitFareMode[];
  adultOneWayCents: number;
  dayPassCents?: number;
  fareCapDailyCents?: number;
  fareCapWeeklyCents?: number;
  sourceLabel: string;
  sourceUrl?: string;
  updatedAt: string;
  confidence: 'low' | 'medium' | 'high';
};

/** Curated local single-ride adult fares — estimates, not live agency quotes. */
export const TRANSIT_FARE_RULES: TransitFareRule[] = [
  {
    id: 'capmetro-austin',
    agencyName: 'CapMetro',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    regionKeys: ['austin', 'capmetro', 'travis county', 'round rock', 'pflugerville'],
    modes: ['bus'],
    adultOneWayCents: 125,
    sourceLabel: 'CapMetro local fare schedule',
    sourceUrl: 'https://www.capmetro.org/fares',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'capmetro-austin-commuter',
    agencyName: 'CapMetro',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    regionKeys: ['austin', 'capmetro', 'travis county', 'metrorail', 'metro rail', 'red line'],
    modes: ['light_rail', 'commuter_rail', 'rail'],
    adultOneWayCents: 350,
    sourceLabel: 'CapMetro commuter/rail fare schedule',
    sourceUrl: 'https://www.capmetro.org/fares',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'king-county-metro-seattle',
    agencyName: 'King County Metro',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    regionKeys: [
      'seattle',
      'king county',
      'bellevue',
      'redmond',
      'kirkland',
      'renton',
      'tacoma',
      'everett',
      'sea-tac',
      'seatac',
      'pike place',
      'capitol hill',
      'ballard',
      'fremont',
      'issaquah',
      'monroe, wa',
    ],
    modes: ['bus', 'light_rail', 'streetcar'],
    adultOneWayCents: 300,
    sourceLabel: 'King County Metro/ORCA local fare estimate',
    sourceUrl: 'https://kingcounty.gov/en/dept/metro/fares-and-payment/fares',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'sound-transit-seattle',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    regionKeys: ['sound transit', 'link light rail', 'sea-tac', 'seatac', 'northgate', 'uw station'],
    modes: ['light_rail', 'commuter_rail'],
    adultOneWayCents: 300,
    sourceLabel: 'Sound Transit fare estimate',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/how-to-pay/fares',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'la-metro',
    agencyName: 'LA Metro',
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    regionKeys: ['los angeles', 'la metro', 'hollywood', 'santa monica', 'pasadena', 'long beach'],
    modes: ['bus', 'rail', 'subway', 'light_rail'],
    adultOneWayCents: 175,
    sourceLabel: 'LA Metro base fare estimate',
    sourceUrl: 'https://www.metro.net/riding/fares/',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'mta-nyc',
    agencyName: 'MTA',
    city: 'New York',
    state: 'NY',
    country: 'US',
    regionKeys: [
      'new york',
      'nyc',
      'manhattan',
      'brooklyn',
      'queens',
      'bronx',
      'staten island',
      'jfk',
      'lga',
      'newark airport',
    ],
    modes: ['bus', 'subway'],
    adultOneWayCents: 300,
    sourceLabel: 'MTA subway/local bus fare estimate',
    sourceUrl: 'https://new.mta.info/fares',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'cta-chicago',
    agencyName: 'CTA',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    regionKeys: ['chicago', 'cta', 'cook county', 'loop', 'wrigleyville'],
    modes: ['bus', 'subway', 'rail'],
    adultOneWayCents: 250,
    sourceLabel: 'CTA fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'muni-sf',
    agencyName: 'SF Muni',
    city: 'San Francisco',
    state: 'CA',
    country: 'US',
    regionKeys: ['san francisco', 'sf muni', 'muni', 'oakland', 'berkeley', 'bart'],
    modes: ['bus', 'light_rail', 'streetcar'],
    adultOneWayCents: 250,
    sourceLabel: 'SF Muni fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'wmata-dc',
    agencyName: 'WMATA',
    city: 'Washington',
    state: 'DC',
    country: 'US',
    regionKeys: ['washington dc', 'washington, dc', 'wmata', 'metro dc', 'arlington', 'bethesda'],
    modes: ['bus', 'subway', 'rail'],
    adultOneWayCents: 250,
    sourceLabel: 'WMATA fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'mbta-boston',
    agencyName: 'MBTA',
    city: 'Boston',
    state: 'MA',
    country: 'US',
    regionKeys: ['boston', 'mbta', 'cambridge', 'somerville', 'brookline'],
    modes: ['bus', 'subway', 'commuter_rail'],
    adultOneWayCents: 240,
    sourceLabel: 'MBTA fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'marta-atlanta',
    agencyName: 'MARTA',
    city: 'Atlanta',
    state: 'GA',
    country: 'US',
    regionKeys: ['atlanta', 'marta', 'decatur', 'buckhead'],
    modes: ['bus', 'rail'],
    adultOneWayCents: 250,
    sourceLabel: 'MARTA fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'rtd-denver',
    agencyName: 'RTD',
    city: 'Denver',
    state: 'CO',
    country: 'US',
    regionKeys: ['denver', 'rtd', 'aurora', 'boulder'],
    modes: ['bus', 'light_rail', 'commuter_rail'],
    adultOneWayCents: 300,
    sourceLabel: 'RTD fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'trimet-portland',
    agencyName: 'TriMet',
    city: 'Portland',
    state: 'OR',
    country: 'US',
    regionKeys: ['portland', 'trimet', 'beaverton', 'hillsboro'],
    modes: ['bus', 'light_rail', 'streetcar'],
    adultOneWayCents: 250,
    sourceLabel: 'TriMet fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'dart-dallas',
    agencyName: 'DART',
    city: 'Dallas',
    state: 'TX',
    country: 'US',
    regionKeys: ['dallas', 'dart', 'fort worth', 'plano', 'irving'],
    modes: ['bus', 'light_rail', 'commuter_rail'],
    adultOneWayCents: 300,
    sourceLabel: 'DART fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'metro-houston',
    agencyName: 'METRO',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    regionKeys: ['houston', 'metro houston', 'harris county'],
    modes: ['bus', 'light_rail'],
    adultOneWayCents: 125,
    sourceLabel: 'Houston METRO fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'miami-dade',
    agencyName: 'Miami-Dade Transit',
    city: 'Miami',
    state: 'FL',
    country: 'US',
    regionKeys: ['miami', 'miami-dade', 'dade county', 'brickell'],
    modes: ['bus', 'rail'],
    adultOneWayCents: 225,
    sourceLabel: 'Miami-Dade Transit fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'valley-metro-phoenix',
    agencyName: 'Valley Metro',
    city: 'Phoenix',
    state: 'AZ',
    country: 'US',
    regionKeys: ['phoenix', 'valley metro', 'scottsdale', 'tempe', 'mesa'],
    modes: ['bus', 'light_rail'],
    adultOneWayCents: 200,
    sourceLabel: 'Valley Metro fare estimate',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
];
