export type ParkRideFacilityMode =
  | 'bus'
  | 'rail'
  | 'light_rail'
  | 'commuter_rail'
  | 'brt';

export type ParkRideFacility = {
  id: string;
  name: string;
  agencyName: string;
  city: string;
  state: string;
  country: 'US';
  lat: number;
  lng: number;
  address?: string;
  servedRoutes?: string[];
  modes: ParkRideFacilityMode[];
  parkingCostExpectation: 'free' | 'paid' | 'permit' | 'unknown';
  timeLimit?: string;
  overnightAllowed?: boolean | 'unknown';
  sourceLabel: string;
  sourceUrl?: string;
  updatedAt: string;
  confidence: 'low' | 'medium' | 'high';
};

export type ParkRideMetroMarket = {
  id: string;
  name: string;
  agencyNames: string[];
  regionKeys: string[];
  states: string[];
  centerLat: number;
  centerLng: number;
  radiusMiles: number;
  tripPlannerUrl?: string;
  facilities: ParkRideFacility[];
};

const AUSTIN_CAPMETRO_FACILITIES: ParkRideFacility[] = [
  {
    id: 'capmetro-plaza-saltillo',
    name: 'Plaza Saltillo Station Park & Ride',
    agencyName: 'CapMetro',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    lat: 30.2622,
    lng: -97.7274,
    address: '1050 E 5th St, Austin, TX 78702',
    servedRoutes: ['MetroRail Red Line', 'Routes 4, 7, 10, 20'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'CapMetro Park & Ride',
    sourceUrl: 'https://www.capmetro.org/park-ride',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'capmetro-mlk-jr',
    name: 'MLK Jr Station Park & Ride',
    agencyName: 'CapMetro',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    lat: 30.2794,
    lng: -97.7142,
    address: '1600 E Martin Luther King Jr Blvd, Austin, TX 78702',
    servedRoutes: ['MetroRail Red Line', 'Routes 18, 20, 22'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'CapMetro Park & Ride',
    sourceUrl: 'https://www.capmetro.org/park-ride',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'capmetro-kramer',
    name: 'Kramer Station Park & Ride',
    agencyName: 'CapMetro',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    lat: 30.3927,
    lng: -97.7254,
    address: '2910 Kramer Ln, Austin, TX 78758',
    servedRoutes: ['MetroRail Red Line', 'Routes 383, 392, 466'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'CapMetro Park & Ride',
    sourceUrl: 'https://www.capmetro.org/park-ride',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'capmetro-lakeline',
    name: 'Lakeline Station Park & Ride',
    agencyName: 'CapMetro',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    lat: 30.481,
    lng: -97.7892,
    address: '13700 Lyndhurst St, Austin, TX 78717',
    servedRoutes: ['MetroRail Red Line', 'Routes 383, 465, 987'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'CapMetro Park & Ride',
    sourceUrl: 'https://www.capmetro.org/park-ride',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
];

const HOUSTON_METRO_FACILITIES: ParkRideFacility[] = [
  {
    id: 'metro-fannin-south',
    name: 'Fannin South Park & Ride',
    agencyName: 'METRO',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    lat: 29.6743,
    lng: -95.4151,
    address: '1604 W Bellfort Ave, Houston, TX 77054',
    servedRoutes: ['METRORail Red Line', 'Routes 2, 9, 15'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'METRO Park & Ride',
    sourceUrl: 'https://www.ridemetro.org/riding-metro/park-ride-lots',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'metro-northwest-transit',
    name: 'Northwest Transit Center Park & Ride',
    agencyName: 'METRO',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    lat: 29.8052,
    lng: -95.4734,
    address: '1855 Northwest Fwy, Houston, TX 77092',
    servedRoutes: ['Routes 11, 18, 24, 36, 86'],
    modes: ['bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'METRO Park & Ride',
    sourceUrl: 'https://www.ridemetro.org/riding-metro/park-ride-lots',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'metro-kingsland',
    name: 'Kingsland Park & Ride',
    agencyName: 'METRO',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    lat: 29.7961,
    lng: -95.5083,
    address: 'Kingsland Blvd & I-10, Houston, TX 77024',
    servedRoutes: ['Routes 46, 47, 49'],
    modes: ['bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'METRO Park & Ride',
    sourceUrl: 'https://www.ridemetro.org/riding-metro/park-ride-lots',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'metro-westpark',
    name: 'Westpark Lower Tier Park & Ride',
    agencyName: 'METRO',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    lat: 29.7214,
    lng: -95.5121,
    address: 'Westpark Dr & Beltway 8, Houston, TX 77082',
    servedRoutes: ['Routes 2, 9, 22, 53'],
    modes: ['bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'METRO Park & Ride',
    sourceUrl: 'https://www.ridemetro.org/riding-metro/park-ride-lots',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
];

const SEATTLE_FACILITIES: ParkRideFacility[] = [
  {
    id: 'northgate-station-garage',
    name: 'Northgate Station Garage / Park-and-Ride A',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.7025,
    lng: -122.3274,
    address: '10300 1st Ave NE, Seattle, WA 98125',
    servedRoutes: ['Link 1 Line', 'Routes 40, 41, 45, 75, 155, 301, 303, 345, 346, 347, 348, 373, 556, 810, 821, 860'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'paid',
    timeLimit: 'Overnight rules vary by lot',
    overnightAllowed: false,
    sourceLabel: 'Sound Transit parking',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/parking',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'mountlake-terrace-station',
    name: 'Mountlake Terrace Station',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.7883,
    lng: -122.3117,
    address: '24000 56th Ave W, Mountlake Terrace, WA 98043',
    servedRoutes: ['Link 1 Line', 'Routes 112, 115, 116, 118, 120, 130, 345, 346, 347, 348, 510, 511, 512, 522, 550, 554, 556'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'paid',
    timeLimit: 'Overnight rules vary by lot',
    overnightAllowed: false,
    sourceLabel: 'Sound Transit parking',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/parking',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'lynnwood-city-center',
    name: 'Lynnwood City Center Station',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.8209,
    lng: -122.2931,
    address: '19700 48th Ave W, Lynnwood, WA 98036',
    servedRoutes: ['Link 1 Line', 'Routes 115, 116, 120, 130, 345, 346, 347, 348, 510, 511, 512, 522, 550, 554, 556'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'paid',
    timeLimit: 'Overnight rules vary by lot',
    overnightAllowed: false,
    sourceLabel: 'Sound Transit parking',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/parking',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'mercer-island-park-and-ride',
    name: 'Mercer Island Park-and-Ride',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.5837,
    lng: -122.2322,
    address: '7600 SE 32nd St, Mercer Island, WA 98040',
    servedRoutes: ['Routes 204, 208, 212, 214, 216, 217, 218, 219, 221, 226, 227, 240, 245, 248, 250, 255, 271, 272, 301, 303, 550, 554, 556'],
    modes: ['bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'Sound Transit parking',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/parking/parking-locations/mercer-island-park-ride',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'redmond-technology-station',
    name: 'Redmond Technology Station',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.6762,
    lng: -122.1238,
    address: '16160 NE 83rd St, Redmond, WA 98052',
    servedRoutes: ['Link 2 Line', 'Routes 221, 245, 248, 250, 255, 271, 272, 301, 303, 342, 545, 550, 554, 556'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'paid',
    timeLimit: 'Overnight rules vary by lot',
    overnightAllowed: false,
    sourceLabel: 'Sound Transit parking',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/parking',
    updatedAt: '2026-06-01',
    confidence: 'high',
  },
  {
    id: 'redmond-transit-center',
    name: 'Redmond Transit Center',
    agencyName: 'King County Metro',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.6456,
    lng: -122.1304,
    address: '156th Ave NE & NE 40th St, Redmond, WA 98052',
    servedRoutes: ['Routes 221, 245, 248, 250, 255, 271, 272, 301, 303, 342, 545, 550, 554, 556'],
    modes: ['bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: 'King County Metro Park & Ride',
    sourceUrl: 'https://kingcounty.gov/en/dept/metro/travel-options/bus/park-and-ride',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'tukwila-international-blvd',
    name: 'Tukwila International Blvd Station',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.4642,
    lng: -122.2881,
    address: '15425 52nd Ave S, Tukwila, WA 98188',
    servedRoutes: ['Link 1 Line', 'Routes 124, 128, 131, 132, 140, 150, 152, 156, 158, 159, 164, 168, 174, 180, 181, 193, 194, 199, 200'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'paid',
    timeLimit: 'Overnight rules vary by lot',
    overnightAllowed: false,
    sourceLabel: 'Sound Transit parking',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/parking',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'angle-lake-station',
    name: 'Angle Lake Station',
    agencyName: 'Sound Transit',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    lat: 47.4422,
    lng: -122.2931,
    address: '20055 24th Ave S, SeaTac, WA 98198',
    servedRoutes: ['Link 1 Line', 'Routes 124, 128, 131, 132, 140, 150, 152, 156, 158, 159, 164, 168, 174, 180, 181, 193, 194, 199, 200'],
    modes: ['light_rail', 'bus'],
    parkingCostExpectation: 'paid',
    timeLimit: 'Overnight rules vary by lot',
    overnightAllowed: false,
    sourceLabel: 'Sound Transit parking',
    sourceUrl: 'https://www.soundtransit.org/ride-with-us/parking',
    updatedAt: '2026-06-01',
    confidence: 'medium',
  },
  {
    id: 'wsdot-narrows-park-ride',
    name: 'Narrows Park & Ride',
    agencyName: 'WSDOT',
    city: 'Tacoma',
    state: 'WA',
    country: 'US',
    lat: 47.2522,
    lng: -122.5361,
    address: 'Hwy 16 & Jackson Ave, Tacoma, WA 98466',
    servedRoutes: ['Routes 102, 117, 216, 586'],
    modes: ['bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Often 48 hours max; verify signs',
    overnightAllowed: false,
    sourceLabel: 'WSDOT Park & Ride',
    sourceUrl: 'https://wsdot.wa.gov/travel/roads-bridges/toll-roads/parking',
    updatedAt: '2026-06-01',
    confidence: 'low',
  },
];

function stubFacility(args: {
  id: string;
  name: string;
  agencyName: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
  address: string;
  sourceUrl?: string;
}): ParkRideFacility {
  return {
    ...args,
    country: 'US',
    modes: ['bus'],
    parkingCostExpectation: 'free',
    timeLimit: 'Same-day commuter use typical',
    overnightAllowed: false,
    sourceLabel: `${args.agencyName} Park & Ride`,
    updatedAt: '2026-06-01',
    confidence: 'medium',
  };
}

export const PARK_RIDE_METRO_MARKETS: ParkRideMetroMarket[] = [
  {
    id: 'austin',
    name: 'Austin',
    agencyNames: ['CapMetro'],
    regionKeys: ['austin', 'capmetro', 'travis county', 'round rock', 'pflugerville', 'cedar park'],
    states: ['TX'],
    centerLat: 30.2672,
    centerLng: -97.7431,
    radiusMiles: 35,
    tripPlannerUrl: 'https://www.capmetro.org/plan/schedules',
    facilities: AUSTIN_CAPMETRO_FACILITIES,
  },
  {
    id: 'houston',
    name: 'Houston',
    agencyNames: ['METRO'],
    regionKeys: ['houston', 'harris county', 'ridemetro', 'the woodlands', 'katy', 'sugar land'],
    states: ['TX'],
    centerLat: 29.7604,
    centerLng: -95.3698,
    radiusMiles: 40,
    tripPlannerUrl: 'https://www.ridemetro.org/',
    facilities: HOUSTON_METRO_FACILITIES,
  },
  {
    id: 'dallas',
    name: 'Dallas',
    agencyNames: ['DART'],
    regionKeys: ['dallas', 'dart', 'fort worth', 'plano', 'irving', 'arlington'],
    states: ['TX'],
    centerLat: 32.7767,
    centerLng: -96.797,
    radiusMiles: 40,
    tripPlannerUrl: 'https://www.dart.org/',
    facilities: [
      stubFacility({
        id: 'dart-parker-road',
        name: 'Parker Road Station Park & Ride',
        agencyName: 'DART',
        city: 'Plano',
        state: 'TX',
        lat: 33.0393,
        lng: -96.6987,
        address: '2600 Archerwood Ave, Plano, TX 75074',
        sourceUrl: 'https://www.dart.org/riding/parkandride.asp',
      }),
      stubFacility({
        id: 'dart-frankford',
        name: 'Frankford Station Park & Ride',
        agencyName: 'DART',
        city: 'Dallas',
        state: 'TX',
        lat: 32.9897,
        lng: -96.8422,
        address: '4847 Frankford Rd, Dallas, TX 75287',
        sourceUrl: 'https://www.dart.org/riding/parkandride.asp',
      }),
    ],
  },
  {
    id: 'san-antonio',
    name: 'San Antonio',
    agencyNames: ['VIA'],
    regionKeys: ['san antonio', 'via metropolitan', 'bexar county'],
    states: ['TX'],
    centerLat: 29.4241,
    centerLng: -98.4936,
    radiusMiles: 30,
    tripPlannerUrl: 'https://www.viainfo.net/',
    facilities: [
      stubFacility({
        id: 'via-ellis',
        name: 'Ellis Park & Ride',
        agencyName: 'VIA',
        city: 'San Antonio',
        state: 'TX',
        lat: 29.4522,
        lng: -98.5001,
        address: 'Ellis Alley Transit Center area, San Antonio, TX',
        sourceUrl: 'https://www.viainfo.net/park-ride-lots',
      }),
    ],
  },
  {
    id: 'seattle',
    name: 'Seattle',
    agencyNames: ['Sound Transit', 'King County Metro'],
    regionKeys: [
      'seattle',
      'bellevue',
      'redmond',
      'lynnwood',
      'tacoma',
      'everett',
      'kirkland',
      'issaquah',
      'mercer island',
      'mountlake terrace',
      'northgate',
      'seatac',
      'sea-tac',
      'king county',
      'sound transit',
    ],
    states: ['WA'],
    centerLat: 47.6062,
    centerLng: -122.3321,
    radiusMiles: 45,
    tripPlannerUrl: 'https://www.soundtransit.org/tripplanner',
    facilities: SEATTLE_FACILITIES,
  },
  {
    id: 'portland',
    name: 'Portland',
    agencyNames: ['TriMet'],
    regionKeys: ['portland', 'trimet', 'beaverton', 'hillsboro', 'gresham'],
    states: ['OR'],
    centerLat: 45.5152,
    centerLng: -122.6784,
    radiusMiles: 35,
    tripPlannerUrl: 'https://trimet.org/',
    facilities: [
      stubFacility({
        id: 'trimet-sunset',
        name: 'Sunset Transit Center Park & Ride',
        agencyName: 'TriMet',
        city: 'Portland',
        state: 'OR',
        lat: 45.5105,
        lng: -122.7827,
        address: '10200 SW Naito Pkwy, Portland, OR 97219',
        sourceUrl: 'https://trimet.org/parkandride',
      }),
    ],
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    agencyNames: ['LA Metro', 'Metrolink'],
    regionKeys: ['los angeles', 'la metro', 'hollywood', 'pasadena', 'santa monica', 'long beach'],
    states: ['CA'],
    centerLat: 34.0522,
    centerLng: -118.2437,
    radiusMiles: 45,
    tripPlannerUrl: 'https://www.metro.net/',
    facilities: [
      stubFacility({
        id: 'la-metro-north-hollywood',
        name: 'North Hollywood Station Park & Ride',
        agencyName: 'LA Metro',
        city: 'Los Angeles',
        state: 'CA',
        lat: 34.1686,
        lng: -118.3788,
        address: '11250 Chandler Blvd, North Hollywood, CA 91601',
        sourceUrl: 'https://www.metro.net/riding/park-ride-lots/',
      }),
    ],
  },
  {
    id: 'sf-bay-area',
    name: 'San Francisco Bay Area',
    agencyNames: ['BART', 'AC Transit'],
    regionKeys: ['san francisco', 'oakland', 'berkeley', 'bart', 'bay area', 'silicon valley', 'san jose'],
    states: ['CA'],
    centerLat: 37.7749,
    centerLng: -122.4194,
    radiusMiles: 50,
    tripPlannerUrl: 'https://www.bart.gov/',
    facilities: [
      stubFacility({
        id: 'bart-pleasant-hill',
        name: 'Pleasant Hill / Contra Costa Centre Station',
        agencyName: 'BART',
        city: 'Concord',
        state: 'CA',
        lat: 37.9284,
        lng: -122.0619,
        address: '65 Crescent Dr, Pleasant Hill, CA 94523',
        sourceUrl: 'https://www.bart.gov/stations',
      }),
    ],
  },
  {
    id: 'chicago',
    name: 'Chicago',
    agencyNames: ['CTA', 'Metra', 'Pace'],
    regionKeys: ['chicago', 'cta', 'metra', 'cook county', 'evanston', 'skokie'],
    states: ['IL'],
    centerLat: 41.8781,
    centerLng: -87.6298,
    radiusMiles: 40,
    tripPlannerUrl: 'https://www.transitchicago.com/',
    facilities: [
      stubFacility({
        id: 'cta-harlem',
        name: 'Harlem Blue Line Park & Ride',
        agencyName: 'CTA',
        city: 'Chicago',
        state: 'IL',
        lat: 41.9825,
        lng: -87.8074,
        address: 'Harlem Ave & I-290, Chicago, IL',
        sourceUrl: 'https://www.transitchicago.com/',
      }),
    ],
  },
  {
    id: 'nyc-nj',
    name: 'New York / New Jersey',
    agencyNames: ['MTA', 'NJ Transit', 'Metro-North', 'LIRR'],
    regionKeys: ['new york', 'nyc', 'manhattan', 'brooklyn', 'queens', 'bronx', 'jersey city', 'newark'],
    states: ['NY', 'NJ'],
    centerLat: 40.7128,
    centerLng: -74.006,
    radiusMiles: 45,
    tripPlannerUrl: 'https://new.mta.info/',
    facilities: [
      stubFacility({
        id: 'nj-transit-hamilton',
        name: 'Hamilton Station Park & Ride',
        agencyName: 'NJ Transit',
        city: 'Hamilton',
        state: 'NJ',
        lat: 40.2551,
        lng: -74.6532,
        address: '850 Sloan Ave, Hamilton Township, NJ 08690',
        sourceUrl: 'https://www.njtransit.com/',
      }),
    ],
  },
  {
    id: 'dc',
    name: 'Washington DC',
    agencyNames: ['WMATA'],
    regionKeys: ['washington dc', 'washington, dc', 'wmata', 'arlington', 'bethesda', 'silver spring'],
    states: ['DC', 'VA', 'MD'],
    centerLat: 38.9072,
    centerLng: -77.0369,
    radiusMiles: 40,
    tripPlannerUrl: 'https://www.wmata.com/',
    facilities: [
      stubFacility({
        id: 'wmata-greenbelt',
        name: 'Greenbelt Station Park & Ride',
        agencyName: 'WMATA',
        city: 'Greenbelt',
        state: 'MD',
        lat: 39.011,
        lng: -76.9113,
        address: '5717 Greenbelt Metro Dr, Greenbelt, MD 20740',
        sourceUrl: 'https://www.wmata.com/',
      }),
    ],
  },
  {
    id: 'boston',
    name: 'Boston',
    agencyNames: ['MBTA'],
    regionKeys: ['boston', 'mbta', 'cambridge', 'somerville', 'brookline'],
    states: ['MA'],
    centerLat: 42.3601,
    centerLng: -71.0589,
    radiusMiles: 35,
    tripPlannerUrl: 'https://www.mbta.com/',
    facilities: [
      stubFacility({
        id: 'mbta-alewife',
        name: 'Alewife Station Park & Ride',
        agencyName: 'MBTA',
        city: 'Cambridge',
        state: 'MA',
        lat: 42.3959,
        lng: -71.1413,
        address: 'Alewife Brook Pkwy, Cambridge, MA 02138',
        sourceUrl: 'https://www.mbta.com/',
      }),
    ],
  },
  {
    id: 'denver',
    name: 'Denver',
    agencyNames: ['RTD'],
    regionKeys: ['denver', 'rtd', 'aurora', 'boulder', 'lakewood'],
    states: ['CO'],
    centerLat: 39.7392,
    centerLng: -104.9903,
    radiusMiles: 40,
    tripPlannerUrl: 'https://www.rtd-denver.com/',
    facilities: [
      stubFacility({
        id: 'rtd-littleton',
        name: 'Littleton Mineral Station Park & Ride',
        agencyName: 'RTD',
        city: 'Littleton',
        state: 'CO',
        lat: 39.5807,
        lng: -105.0193,
        address: '8990 S Santa Fe Dr, Littleton, CO 80125',
        sourceUrl: 'https://www.rtd-denver.com/',
      }),
    ],
  },
  {
    id: 'atlanta',
    name: 'Atlanta',
    agencyNames: ['MARTA'],
    regionKeys: ['atlanta', 'marta', 'decatur', 'buckhead', 'midtown atlanta'],
    states: ['GA'],
    centerLat: 33.749,
    centerLng: -84.388,
    radiusMiles: 35,
    tripPlannerUrl: 'https://www.itsmarta.com/',
    facilities: [
      stubFacility({
        id: 'marta-doraville',
        name: 'Doraville Station Park & Ride',
        agencyName: 'MARTA',
        city: 'Doraville',
        state: 'GA',
        lat: 33.8998,
        lng: -84.2811,
        address: '6000 New Peachtree Rd, Doraville, GA 30340',
        sourceUrl: 'https://www.itsmarta.com/',
      }),
    ],
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    agencyNames: ['Valley Metro'],
    regionKeys: ['phoenix', 'valley metro', 'scottsdale', 'tempe', 'mesa'],
    states: ['AZ'],
    centerLat: 33.4484,
    centerLng: -112.074,
    radiusMiles: 40,
    tripPlannerUrl: 'https://www.valleymetro.org/',
    facilities: [
      stubFacility({
        id: 'valley-metro-19th-ave',
        name: '19th Ave/Dunlap Park & Ride',
        agencyName: 'Valley Metro',
        city: 'Phoenix',
        state: 'AZ',
        lat: 33.5678,
        lng: -112.0996,
        address: 'N 19th Ave & W Dunlap Ave, Phoenix, AZ',
        sourceUrl: 'https://www.valleymetro.org/',
      }),
    ],
  },
  {
    id: 'miami',
    name: 'Miami',
    agencyNames: ['Miami-Dade Transit', 'Tri-Rail'],
    regionKeys: ['miami', 'miami-dade', 'brickell', 'doral', 'fort lauderdale', 'tri-rail'],
    states: ['FL'],
    centerLat: 25.7617,
    centerLng: -80.1918,
    radiusMiles: 40,
    tripPlannerUrl: 'https://www.miamidade.gov/transit/',
    facilities: [
      stubFacility({
        id: 'miami-dade-dadeland',
        name: 'Dadeland South Station Park & Ride',
        agencyName: 'Miami-Dade Transit',
        city: 'Miami',
        state: 'FL',
        lat: 25.7027,
        lng: -80.3135,
        address: '9100 S Dadeland Blvd, Miami, FL 33156',
        sourceUrl: 'https://www.miamidade.gov/transit/',
      }),
    ],
  },
];

const FACILITY_BY_ID = new Map<string, ParkRideFacility>(
  PARK_RIDE_METRO_MARKETS.flatMap((market) =>
    market.facilities.map((facility) => [facility.id, facility] as const),
  ),
);

export function getParkRideFacilityById(id: string): ParkRideFacility | undefined {
  return FACILITY_BY_ID.get(id);
}

export function getParkRideFacilitiesForMetro(metroId: string): ParkRideFacility[] {
  return PARK_RIDE_METRO_MARKETS.find((market) => market.id === metroId)?.facilities ?? [];
}
